---
jobs:
- name: build-cncjs-docker-image
  public: true
  serial: true
  plan:
  - get: cncjs-repo
    trigger: true
  - put: docker-image
    params:
      build: cncjs-repo

- name: build-cncjs-docker-image
  public: true
  serial: true
  plan:
  - get: cncjs-docker-repo
  - put: docker-image
    params:
      build: cncjs-docker-repo
    
resources:

- name: cncjs-repo
  type: git
  source:
    uri: https://github.com/cncjs/cncjs
    tag_filter: "*"
    branch: master

- name: cncjs-docker-repo
  type: git
  source:
    uri: https://github.com/danhigham/cncjs-docker
    branch: master
  
- name: docker-image
  type: docker-image
  source:
    username: {{harbor-username}}
    password: {{harbor-password}}
    repository: {{cncjs-harbor-repo}}

- name: cnc-docker-image
  type: docker-image
  source:
    username: {{harbor-username}}
    password: {{harbor-password}}
    repository: {{cncjs-socat-harbor-repo}}
